### ISSUE TITLE
found issue in narrative tag after generating xml instance of any particular template.

### ISSUE THREAD

**Issue by saurabhrasp** [ppazos/openEHR-OPT#31]
Just to inform you, we found one issue in sample instance generated by openehr-opt application.
Issue is related to value of 'narrative' tag.
Every time instance generated for any template narrative tag value is like below, i.e closing double square bracket is missing.

`<narrative>
        <value>[[Blood_glucose_management:::INSTRUCTION_NARRATIVE_VALUE</value>
</narrative>`

But it should be like below.

`<narrative>
        <value>[[Blood_glucose_management:::INSTRUCTION_NARRATIVE_VALUE]]</value>
</narrative>`

we also checked the 'openehr-opt' app code and found that in file "XmlInstanceGeneratorTagged.groovy" at line 876 there is some code like below.
![image](https://user-images.githubusercontent.com/23055899/36774927-fa1a938a-1c85-11e8-8604-6e2a41f0800c.png)

it should be like below to get the intended result.
`builder.narrative() {
            value('[['+ label +':::INSTRUCTION_NARRATIVE_VALUE]]')
}`

**Comment by ppazos** [comment]
@saurabhrasp just committed a fix, please pull the repo again. Thanks.
